In [1]:
import pandas as pd

data = {
    'Order_ID': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
                 1011,1012,1013,1014,1015,1016,1017,1018,1019,1020],

    'Date': ['2026-01-01','2026-01-02','2026-01-03','2026-01-04','2026-01-05',
             '2026-01-06','2026-01-07','2026-01-08','2026-01-09','2026-01-10',
             '2026-01-11','2026-01-12','2026-01-13','2026-01-14','2026-01-15',
             '2026-01-16','2026-01-17','2026-01-18','2026-01-19','2026-01-20'],

    'Customer': ['Rahul','Priya','Amit','Sneha','Rahul','Arjun','Priya','Amit',
                 'Sneha','Arjun','Rahul','Priya','Amit','Sneha','Arjun','Rahul',
                 'Priya','Amit','Sneha','Arjun'],

    'City': ['Delhi','Mumbai','Kolkata','Delhi','Mumbai','Chennai','Delhi',
             'Mumbai','Kolkata','Chennai','Delhi','Mumbai','Kolkata','Chennai',
             'Delhi','Mumbai','Kolkata','Chennai','Delhi','Mumbai'],

    'Product': ['Laptop','Mobile','Tablet','Mobile','Laptop','Tablet','Laptop',
                'Mobile','Laptop','Mobile','Tablet','Laptop','Mobile','Tablet',
                'Mobile','Tablet','Laptop','Mobile','Laptop','Tablet'],

    'Quantity': [2,3,4,2,1,3,2,4,1,2,5,2,3,4,3,2,2,4,1,3],

    'Price_Per_Unit': [55000,25000,18000,28000,60000,20000,58000,24000,
                       62000,26000,19000,57000,27000,21000,25000,22000,
                       59000,23000,61000,19000],

    'Sales': [110000,75000,72000,56000,60000,60000,116000,96000,62000,52000,
              95000,114000,81000,84000,75000,44000,118000,92000,61000,57000]
}

df = pd.DataFrame(data)

print(df)

    Order_ID        Date Customer     City Product  Quantity  Price_Per_Unit  \
0       1001  2026-01-01    Rahul    Delhi  Laptop         2           55000
1       1002  2026-01-02    Priya   Mumbai  Mobile         3           25000
2       1003  2026-01-03     Amit  Kolkata  Tablet         4           18000
3       1004  2026-01-04    Sneha    Delhi  Mobile         2           28000
4       1005  2026-01-05    Rahul   Mumbai  Laptop         1           60000
5       1006  2026-01-06    Arjun  Chennai  Tablet         3           20000
6       1007  2026-01-07    Priya    Delhi  Laptop         2           58000
7       1008  2026-01-08     Amit   Mumbai  Mobile         4           24000
8       1009  2026-01-09    Sneha  Kolkata  Laptop         1           62000
9       1010  2026-01-10    Arjun  Chennai  Mobile         2           26000
10      1011  2026-01-11    Rahul    Delhi  Tablet         5           19000
11      1012  2026-01-12    Priya   Mumbai  Laptop         2           57000
12      1013  2026-01-13     Amit  Kolkata  Mobile         3           27000
13      1014  2026-01-14    Sneha  Chennai  Tablet         4           21000
14      1015  2026-01-15    Arjun    Delhi  Mobile         3           25000
15      1016  2026-01-16    Rahul   Mumbai  Tablet         2           22000
16      1017  2026-01-17    Priya  Kolkata  Laptop         2           59000
17      1018  2026-01-18     Amit  Chennai  Mobile         4           23000
18      1019  2026-01-19    Sneha    Delhi  Laptop         1           61000
19      1020  2026-01-20    Arjun   Mumbai  Tablet         3           19000

     Sales
0   110000
1    75000
2    72000
3    56000
4    60000
5    60000
6   116000
7    96000
8    62000
9    52000
10   95000
11  114000
12   81000
13   84000
14   75000
15   44000
16  118000
17   92000
18   61000
19   57000

In [2]:
#Display the first 5 rows of the dataset.
df.head()

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000

In [3]:
#Display the last 5 rows.
df.tail()

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000

In [4]:
#Find the number of rows and columns.
df.shape

(20, 8)

In [6]:
#Display all column names.
df.columns

Index(['Order_ID', 'Date', 'Customer', 'City', 'Product', 'Quantity',
       'Price_Per_Unit', 'Sales'],
      dtype='object')

In [7]:
#Display the data types of all columns.
df.dtypes

Order_ID           int64
Date              object
Customer          object
City              object
Product           object
Quantity           int64
Price_Per_Unit     int64
Sales              int64
dtype: object

In [8]:
#Check whether the dataset contains missing values.
df.isnull().sum()

Order_ID          0
Date              0
Customer          0
City              0
Product           0
Quantity          0
Price_Per_Unit    0
Sales             0
dtype: int64

In [9]:
#Find the total number of orders.
df['Order_ID'].nunique()

20

In [10]:
#Find the number of unique customers
df['Customer'].nunique()

5

In [11]:
#Find the number of unique cities
df['City'].nunique()

4

In [12]:
#Find the number of unique products
df['Product'].nunique()

3

In [13]:
#Display all unique cities
df['City'].unique()

array(['Delhi', 'Mumbai', 'Kolkata', 'Chennai'], dtype=object)

In [14]:
#Display all unique products
df['Product'].unique()

array(['Laptop', 'Mobile', 'Tablet'], dtype=object)

In [16]:
#Find the total quantity sold
df['Quantity'].sum()

np.int64(53)

In [17]:
#Find the total sales across all orders
df['Sales'].sum()

np.int64(1580000)

In [18]:
#Find the average sales value
df['Sales'].mean()

np.float64(79000.0)

In [19]:
#find all orders where Sales > 50000
df[df['Sales'] > 50000]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000

In [20]:
#Find all orders from Delhi
df[df['City'] == 'Delhi']

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000

In [21]:
#Find all orders from Mumbai
df[df['City'] == 'Mumbai']

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000

In [22]:
#Find all orders where the product is Laptop
df[df['Product'] == 'Laptop']

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000

In [23]:
#Find all orders where the product is Mobile
df[df['Product'] == 'Mobile']

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000

In [24]:
#Find all orders where Quantity >= 3
df[df['Quantity'] >= 3]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000

In [26]:
#Find all orders where Sales > 100000 
df[df['Sales'] > 100000]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000

In [28]:
#Find Laptop orders where Sales > 50000
df[(df['Product'] == 'Laptop') &(df['Sales'] > 50000)]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000

In [29]:
#Find orders from Delhi where Sales > 70000
df[(df['City'] == 'Delhi') &(df['Sales'] > 70000)]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000

In [35]:
#Find orders where the product is either Laptop or Mobile
df[(df['Product']=='Laptop')|(df['Product']=='Mobile')]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000

In [37]:
#Find orders where the quantity is between 2 and 4
df[df['Quantity'].between(2,4)]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000

In [38]:
#Find orders where the customer is Rahul
df[df['Customer'] == 'Rahul']

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000

In [39]:
#Find orders from Chennai where the product is Tablet

df[(df['City'] == 'Chennai') &(df['Product'] == 'Tablet')]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000

In [40]:
#Sort the dataset by Sales in ascending order
df.sort_values('Sales', ascending=True)

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000

In [41]:

#Sort the dataset by Sales in descending order
df.sort_values('Sales', ascending=False)

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000

In [42]:
#Find the top 5 highest-sales orders
df.nlargest(5, 'Sales')

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000

In [43]:
 #Find the bottom 5 lowest-sales orders
df.nsmallest(5, 'Sales')

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000

In [44]:
#Find the top 3 orders based on quantity
df.sort_values('Quantity',ascending=False).head(3)

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000

In [46]:
#Sort the dataset by Price_Per_Unit from highest to lowest
df.sort_values('Price_Per_Unit', ascending=False)

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
8,1009,2026-01-09,Sneha,Kolkata,Laptop,1,62000,62000
18,1019,2026-01-19,Sneha,Delhi,Laptop,1,61000,61000
4,1005,2026-01-05,Rahul,Mumbai,Laptop,1,60000,60000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
3,1004,2026-01-04,Sneha,Delhi,Mobile,2,28000,56000
12,1013,2026-01-13,Amit,Kolkata,Mobile,3,27000,81000
9,1010,2026-01-10,Arjun,Chennai,Mobile,2,26000,52000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
14,1015,2026-01-15,Arjun,Delhi,Mobile,3,25000,75000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000
15,1016,2026-01-16,Rahul,Mumbai,Tablet,2,22000,44000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
5,1006,2026-01-06,Arjun,Chennai,Tablet,3,20000,60000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
19,1020,2026-01-20,Arjun,Mumbai,Tablet,3,19000,57000
2,1003,2026-01-03,Amit,Kolkata,Tablet,4,18000,72000

In [47]:
#Find total sales for each city
df.groupby('City')['Sales'].sum()

City
Chennai    288000
Delhi      513000
Kolkata    333000
Mumbai     446000
Name: Sales, dtype: int64

In [48]:
#Find average sales for each city
df.groupby('City')['Sales'].mean()

City
Chennai    72000.000000
Delhi      85500.000000
Kolkata    83250.000000
Mumbai     74333.333333
Name: Sales, dtype: float64

In [49]:
#Find total quantity sold for each city
df.groupby('City')['Quantity'].sum()

City
Chennai    13
Delhi      15
Kolkata    10
Mumbai     15
Name: Quantity, dtype: int64

In [50]:
#Find total sales for each product
df.groupby('Product')['Sales'].sum()

Product
Laptop    641000
Mobile    527000
Tablet    412000
Name: Sales, dtype: int64

In [51]:
#Find average sales for each product
df.groupby('Product')['Sales'].mean()

Product
Laptop    91571.428571
Mobile    75285.714286
Tablet    68666.666667
Name: Sales, dtype: float64

In [52]:
#Find total quantity sold for each product
df.groupby('Product')['Quantity'].sum()

Product
Laptop    11
Mobile    21
Tablet    21
Name: Quantity, dtype: int64

In [53]:
#Find average quantity sold for each product
df.groupby('Product')['Quantity'].mean()

Product
Laptop    1.571429
Mobile    3.000000
Tablet    3.500000
Name: Quantity, dtype: float64

In [54]:
#Find total sales for each customer
df.groupby('Customer')['Sales'].sum()

Customer
Amit     341000
Arjun    244000
Priya    423000
Rahul    309000
Sneha    263000
Name: Sales, dtype: int64

In [55]:
#Find average sales for each customer
df.groupby('Customer')['Sales'].mean()

Customer
Amit      85250.0
Arjun     61000.0
Priya    105750.0
Rahul     77250.0
Sneha     65750.0
Name: Sales, dtype: float64

In [56]:
#Find number of orders for each customer
df.groupby('Customer')['Order_ID'].count()

Customer
Amit     4
Arjun    4
Priya    4
Rahul    4
Sneha    4
Name: Order_ID, dtype: int64

In [57]:
#Find number of orders for each city
df.groupby('City')['Order_ID'].count()

City
Chennai    4
Delhi      6
Kolkata    4
Mumbai     6
Name: Order_ID, dtype: int64

In [58]:
#Find number of orders for each product
df.groupby('Product')['Order_ID'].count()

Product
Laptop    7
Mobile    7
Tablet    6
Name: Order_ID, dtype: int64

In [59]:
#Find average price per unit for each product
df.groupby('Product')['Price_Per_Unit'].mean()

Product
Laptop    58857.142857
Mobile    25428.571429
Tablet    19833.333333
Name: Price_Per_Unit, dtype: float64

In [60]:
#Find maximum sales for each city
df.groupby('City')['Sales'].max()

City
Chennai     92000
Delhi      116000
Kolkata    118000
Mumbai     114000
Name: Sales, dtype: int64

In [61]:
#Find minimum sales for each city
df.groupby('City')['Sales'].min()

City
Chennai    52000
Delhi      56000
Kolkata    62000
Mumbai     44000
Name: Sales, dtype: int64

In [62]:
#Find maximum sales for each product
df.groupby('Product')['Sales'].max()

Product
Laptop    118000
Mobile     96000
Tablet     95000
Name: Sales, dtype: int64

In [63]:
#Find the customer who generated the highest total sales
df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head(1)

Customer
Priya    423000
Name: Sales, dtype: int64

In [67]:
#Find the product with the highest total sales overall
df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(1)

Product
Laptop    641000
Name: Sales, dtype: int64

In [68]:
#Find the city with the highest total sales
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(1)

City
Delhi    513000
Name: Sales, dtype: int64

In [69]:
#find the customer with the highest number of orders
df.groupby('Customer')['Order_ID'].count().sort_values(ascending=False).head(1)

Customer
Amit    4
Name: Order_ID, dtype: int64

In [74]:

#Find the highest-value order in the dataset
df.sort_values('Sales', ascending=False).head(1)

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000

In [82]:
#Find the highest-value order in each city
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(1)

City
Delhi    513000
Name: Sales, dtype: int64

result = df.loc[
    df.groupby('City')['Sales'].idxmax()
]

print(result)

In [84]:
#Find the top-selling product in each city
df.groupby(['City','Product'])['Sales'].sum().sort_values(ascending=False).head(1)

City   Product
Delhi  Laptop     287000
Name: Sales, dtype: int64

In [85]:
#Find the top 3 customers based on total sales
df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head(3)

Customer
Priya    423000
Amit     341000
Rahul    309000
Name: Sales, dtype: int64

In [86]:
#Find the top 3 highest-sales orders
df.nlargest(3, 'Sales')

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000

In [87]:
#Find the average order value for each city
df.groupby('City')['Sales'].mean()

City
Chennai    72000.000000
Delhi      85500.000000
Kolkata    83250.000000
Mumbai     74333.333333
Name: Sales, dtype: float64

In [89]:
#Find total sales and average sales per city using agg()
df.groupby('City')['Sales'].agg(total_sales=('sum'),avg_sales=('mean')).reset_index()

      City  total_sales     avg_sales
0  Chennai       288000  72000.000000
1    Delhi       513000  85500.000000
2  Kolkata       333000  83250.000000
3   Mumbai       446000  74333.333333

In [92]:
#Find the percentage contribution of each city to total sales
city_sales = df.groupby('City', as_index=False)['Sales'].sum()

city_sales['Percentage_Contribution'] = (city_sales['Sales'] / city_sales['Sales'].sum())*100

print(city_sales)

      City   Sales  Percentage_Contribution
0  Chennai  288000                18.227848
1    Delhi  513000                32.468354
2  Kolkata  333000                21.075949
3   Mumbai  446000                28.227848

In [93]:
#Find the percentage contribution of each product to total sales
product_sales = df.groupby('Product', as_index=False)['Sales'].sum()

product_sales['Percentage_Contribution'] = (product_sales['Sales'] / product_sales['Sales'].sum())*100
print(product_sales)

  Product   Sales  Percentage_Contribution
0  Laptop  641000                40.569620
1  Mobile  527000                33.354430
2  Tablet  412000                26.075949

In [95]:
#Find orders where sales are greater than the average sales of their city
city_avg = df.groupby('City')['Sales'].transform('mean')
df[df['Sales'] > city_avg]

,Order_ID,Date,Customer,City,Product,Quantity,Price_Per_Unit,Sales
0,1001,2026-01-01,Rahul,Delhi,Laptop,2,55000,110000
1,1002,2026-01-02,Priya,Mumbai,Mobile,3,25000,75000
6,1007,2026-01-07,Priya,Delhi,Laptop,2,58000,116000
7,1008,2026-01-08,Amit,Mumbai,Mobile,4,24000,96000
10,1011,2026-01-11,Rahul,Delhi,Tablet,5,19000,95000
11,1012,2026-01-12,Priya,Mumbai,Laptop,2,57000,114000
13,1014,2026-01-14,Sneha,Chennai,Tablet,4,21000,84000
16,1017,2026-01-17,Priya,Kolkata,Laptop,2,59000,118000
17,1018,2026-01-18,Amit,Chennai,Mobile,4,23000,92000

In [100]:
#Rank customers based on their total sale
customer_sales = df.groupby('Customer',as_index=False)['Sales'].sum()

customer_sales['Rank'] = (
    customer_sales['Sales']
    .rank(ascending=False, method='dense')
)

customer_sales = customer_sales.sort_values('Rank')

print(customer_sales)

  Customer   Sales  Rank
2    Priya  423000   1.0
0     Amit  341000   2.0
3    Rahul  309000   3.0
4    Sneha  263000   4.0
1    Arjun  244000   5.0

In [101]:
#Rank products within each city based on total sales
city_product_sales = (
    df.groupby(['City', 'Product'], as_index=False)['Sales']
    .sum()
)

city_product_sales['Rank'] = (
    city_product_sales.groupby('City')['Sales']
    .rank(ascending=False, method='dense')
)

print(
    city_product_sales.sort_values(['City', 'Rank'])
)

       City Product   Sales  Rank
0   Chennai  Mobile  144000   1.0
1   Chennai  Tablet  144000   1.0
2     Delhi  Laptop  287000   1.0
3     Delhi  Mobile  131000   2.0
4     Delhi  Tablet   95000   3.0
5   Kolkata  Laptop  180000   1.0
6   Kolkata  Mobile   81000   2.0
7   Kolkata  Tablet   72000   3.0
8    Mumbai  Laptop  174000   1.0
9    Mumbai  Mobile  171000   2.0
10   Mumbai  Tablet  101000   3.0

In [102]:
#Find the top 2 products in each city
df.groupby(['City', 'Product'])['Sales'].sum().sort_values(ascending=False).head(2)

City     Product
Delhi    Laptop     287000
Kolkata  Laptop     180000
Name: Sales, dtype: int64

In [104]:
#Find the top 3 orders for each city
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(3)

City
Delhi      513000
Mumbai     446000
Kolkata    333000
Name: Sales, dtype: int64

In [106]:
#Find the city-product combination with the highest total sales
df.groupby(['City', 'Product'])['Sales'].sum().sort_values(ascending=False).head(1)

City   Product
Delhi  Laptop     287000
Name: Sales, dtype: int64

In [107]:
#Find customers whose total sales are above the average customer sales
customer_sales = (
    df.groupby('Customer', as_index=False)['Sales']
    .sum()
)

average_customer_sales = customer_sales['Sales'].mean()

result = customer_sales[
    customer_sales['Sales'] > average_customer_sales
]

print(result)

  Customer   Sales
0     Amit  341000
2    Priya  423000

In [110]:
#Create a City × Product pivot table showing total sales
pivot_table=pd.pivot_table( data=df,values='Sales',index='City',columns='Product',aggfunc='sum')
print(pivot_table)

Product    Laptop    Mobile    Tablet
City
Chennai       NaN  144000.0  144000.0
Delhi    287000.0  131000.0   95000.0
Kolkata  180000.0   81000.0   72000.0
Mumbai   174000.0  171000.0  101000.0

In [111]:
#Create a City × Product pivot table showing total quantity
pivot_table=pd.pivot_table( data=df,values='Quantity',index='City',columns='Product',aggfunc='sum')
print(pivot_table)

Product  Laptop  Mobile  Tablet
City
Chennai     NaN     6.0     7.0
Delhi       5.0     5.0     5.0
Kolkata     3.0     3.0     4.0
Mumbai      3.0     7.0     5.0

In [112]:
#Find each customer's percentage contribution to total sales
customer_sales = (
    df.groupby('Customer', as_index=False)['Sales']
    .sum()
)

customer_sales['Percentage_Contribution'] = (
    customer_sales['Sales'] / customer_sales['Sales'].sum()
) * 100

print(customer_sales)

  Customer   Sales  Percentage_Contribution
0     Amit  341000                21.582278
1    Arjun  244000                15.443038
2    Priya  423000                26.772152
3    Rahul  309000                19.556962
4    Sneha  263000                16.645570

In [113]:
#Find the product with the highest average sales per order
df.groupby('Product')['Sales'].mean().sort_values(ascending=False).head(1)

Product
Laptop    91571.428571
Name: Sales, dtype: float64

In [114]:
#Find the city with the highest average order value
df.groupby('City')['Sales'].mean().sort_values(ascending=False).head(1)

City
Delhi    85500.0
Name: Sales, dtype: float64

In [115]:
#Convert the Date column to datetime format
df['Date'] = pd.to_datetime(df['Date'])
print(df.dtypes)

Order_ID                   int64
Date              datetime64[ns]
Customer                  object
City                      object
Product                   object
Quantity                   int64
Price_Per_Unit             int64
Sales                      int64
dtype: object

In [116]:
#Find date-wise total sales
result = df.groupby('Date')['Sales'].sum()

print(result)

Date
2026-01-01    110000
2026-01-02     75000
2026-01-03     72000
2026-01-04     56000
2026-01-05     60000
2026-01-06     60000
2026-01-07    116000
2026-01-08     96000
2026-01-09     62000
2026-01-10     52000
2026-01-11     95000
2026-01-12    114000
2026-01-13     81000
2026-01-14     84000
2026-01-15     75000
2026-01-16     44000
2026-01-17    118000
2026-01-18     92000
2026-01-19     61000
2026-01-20     57000
Name: Sales, dtype: int64

In [117]:
#Find date-wise total quantity
result = df.groupby('Date')['Quantity'].sum()

print(result)

Date
2026-01-01    2
2026-01-02    3
2026-01-03    4
2026-01-04    2
2026-01-05    1
2026-01-06    3
2026-01-07    2
2026-01-08    4
2026-01-09    1
2026-01-10    2
2026-01-11    5
2026-01-12    2
2026-01-13    3
2026-01-14    4
2026-01-15    3
2026-01-16    2
2026-01-17    2
2026-01-18    4
2026-01-19    1
2026-01-20    3
Name: Quantity, dtype: int64

In [118]:
#Calculate cumulative sales over time
date_sales = (
    df.groupby('Date', as_index=False)['Sales']
      .sum()
      .sort_values('Date')
)

date_sales['Cumulative_Sales'] = date_sales['Sales'].cumsum()

print(date_sales)

         Date   Sales  Cumulative_Sales
0  2026-01-01  110000            110000
1  2026-01-02   75000            185000
2  2026-01-03   72000            257000
3  2026-01-04   56000            313000
4  2026-01-05   60000            373000
5  2026-01-06   60000            433000
6  2026-01-07  116000            549000
7  2026-01-08   96000            645000
8  2026-01-09   62000            707000
9  2026-01-10   52000            759000
10 2026-01-11   95000            854000
11 2026-01-12  114000            968000
12 2026-01-13   81000           1049000
13 2026-01-14   84000           1133000
14 2026-01-15   75000           1208000
15 2026-01-16   44000           1252000
16 2026-01-17  118000           1370000
17 2026-01-18   92000           1462000
18 2026-01-19   61000           1523000
19 2026-01-20   57000           1580000

In [119]:
#Calculate cumulative sales separately for each city
city_date_sales = (
    df.groupby(['City', 'Date'], as_index=False)['Sales']
      .sum()
      .sort_values(['City', 'Date'])
)

city_date_sales['Cumulative_Sales'] = (
    city_date_sales.groupby('City')['Sales'].cumsum()
)

print(city_date_sales)

       City       Date   Sales  Cumulative_Sales
0   Chennai 2026-01-06   60000             60000
1   Chennai 2026-01-10   52000            112000
2   Chennai 2026-01-14   84000            196000
3   Chennai 2026-01-18   92000            288000
4     Delhi 2026-01-01  110000            110000
5     Delhi 2026-01-04   56000            166000
6     Delhi 2026-01-07  116000            282000
7     Delhi 2026-01-11   95000            377000
8     Delhi 2026-01-15   75000            452000
9     Delhi 2026-01-19   61000            513000
10  Kolkata 2026-01-03   72000             72000
11  Kolkata 2026-01-09   62000            134000
12  Kolkata 2026-01-13   81000            215000
13  Kolkata 2026-01-17  118000            333000
14   Mumbai 2026-01-02   75000             75000
15   Mumbai 2026-01-05   60000            135000
16   Mumbai 2026-01-08   96000            231000
17   Mumbai 2026-01-12  114000            345000
18   Mumbai 2026-01-16   44000            389000
19   Mumbai 2026-01-20   57000            446000

In [121]:
#Find the highest-sales date
df.groupby('Date')['Sales'].sum().sort_values(ascending=False).head(1)

Date
2026-01-17    118000
Name: Sales, dtype: int64

In [124]:
#Find the lowest-sales date
df.groupby('Date')['Sales'].sum().sort_values(ascending=True).head(1)

Date
2026-01-16    44000
Name: Sales, dtype: int64

In [125]:
#Find the average daily sale
df.groupby('Date')['Sales'].mean()

Date
2026-01-01    110000.0
2026-01-02     75000.0
2026-01-03     72000.0
2026-01-04     56000.0
2026-01-05     60000.0
2026-01-06     60000.0
2026-01-07    116000.0
2026-01-08     96000.0
2026-01-09     62000.0
2026-01-10     52000.0
2026-01-11     95000.0
2026-01-12    114000.0
2026-01-13     81000.0
2026-01-14     84000.0
2026-01-15     75000.0
2026-01-16     44000.0
2026-01-17    118000.0
2026-01-18     92000.0
2026-01-19     61000.0
2026-01-20     57000.0
Name: Sales, dtype: float64

In [126]:
#Find month-wise total sales
df['Month'] = df['Date'].dt.to_period('M')

monthly_sales = df.groupby('Month')['Sales'].sum()

print(monthly_sales)

Month
2026-01    1580000
Freq: M, Name: Sales, dtype: int64